### ISSUE TITLE
How to install / use?

### ISSUE THREAD

**Issue by ameissnersofi** [narbsy/hubot-health-check#1]
Hi,

I tried including this in my packages.json and external scripts files, but got an error message:

```bash
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hubot-health-check
npm ERR! 404 
npm ERR! 404  'hubot-health-check' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'hubot'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

How do I go about using this then?

**Comment by narbsy** [comment]
Hi @ameissnersofi, sorry for the delay.

This package isn't hosted on NPM, so you'll have to clone and install from the repo manually.

Shortly after creating this package, I realized that Hubot already had what I wanted, which was a simple URL that I could issue a GET to as a reasonable health check.

If you hit Hubot's root url (i.e. `http://<your_hubot_address>/`), it'll respond with OK.

Hope this helps!

**Comment by ameissnersofi** [comment]
Awesome!  I didn't know that.  I'll try out the url and hopefully get a response.  Thanks for the reply!
